
//! Autogenerated weights for orderbook_engine
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-02-23, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/node-polkadex
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=orderbook_engine
// --extrinsic=*
// --steps=50
// --repeat=20
// --heap-pages=4096
// --output=./pallets/Engine/src/weights.rs


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for orderbook_engine.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> orderbook_engine::WeightInfo for WeightInfo<T> {
	fn settle_trade() -> Weight {
		(114_645_700_000 as Weight)
	}
}
