[package]
authors = ['Polkadex Team ']
edition = '2018'
license = 'Apache 2.0'
name = 'polkadex'
version = '2.0.0'

[dependencies]
polkadex-mainnet-runtime = { path = "../../runtime/mainnet", optional = true }
polkadex-testnet-runtime = { path = "../../runtime/testnet", optional = true }

[features]
mainnet = [
    "polkadex-mainnet-runtime",
]
testnet  = [
    "polkadex-testnet-runtime",
]